-- Code created by Kwik - Copyright: kwiksher.com -- Version: 1.9.7a module(..., package.seeall)  function new() 
    local menuGroup = display.newGroup() 
    local disposeAudios     local disposeTweens     local jig_audio = audio.loadSound(audioDir.."v5.mp3" )     local path = system.pathForFile( "SpoonAndTheMoonPart2.txt", system.DocumentsDirectory ) 
    local file = io.open( path, "w+" ) 
    file:write( _G.kwk_currentPage ) 
    io.close( file ) 

    local drawScreen = function()

		 navigation.DisplayDevelopmentVersion()
		menuGroup.navigator = navigation.InsertNavigation{}


local jig         local CH14PG5  --(2) regular layer        CH14PG5 = display.newImageRect( imageDir.. "p203_ch14pg5.png", 768, 1024 );        CH14PG5.x = 384; CH14PG5.y = 512; CH14PG5.alpha = 1; CH14PG5.oldAlpha = 1        menuGroup:insert(CH14PG5)        menuGroup.CH14PG5 = CH14PG5        local onjigTouch = function(event)           if event.phase=="ended" then               local myChannel = 2              local isChannelPlaying = audio.isChannelPlaying(myChannel)              if isChannelPlaying then                 --nothing              else                 audio.play( jig_audio, {channel=myChannel} )              end           end        end --(10) regular layer        jig = ui.newButton{            defaultSrc=imageDir.."p203_jig.png",            defaultX = 357,            defaultY = 33,            overSrc=imageDir.."p203_jig.png",            overX = 357,            overY = 33,            onRelease=onjigTouch,            id="jigButton"        }        jig.x = 346; jig.y = 417; jig.alpha = 1; jig.oldAlpha = 1        menuGroup:insert(jig)        menuGroup.jig = jig          local function flip (event)           local spacer = 180            if event.phase =="ended" then               if event.xStart < event.x and (event.x - event.xStart) >= spacer then                 if (_G.kwk_currentPage > 1) then                      disposeAudios()                     disposeTweens()                     director:changeScene( "page_".._G.kwk_currentPage-1, "moveFromLeft" )                 end              elseif event.xStart > event.x and (event.xStart-event.x) >= spacer then                  if (_G.kwk_currentPage < numPages) then                      disposeAudios()                     disposeTweens()                     director:changeScene("page_".._G.kwk_currentPage+1, "moveFromRight")                 end              end           end        end        CH14PG5:addEventListener("touch", flip)    end    drawScreen()    function disposeAudios(event)                    audio.stop(2); audio.dispose(jig_audio); jig_audio = nil                           audio.stop(3); audio.dispose(kwkBindex_audio); kwkBindex_audio = nil                        end    function disposeTweens(event)       cancelAllTweens();       cancelAllTimers();       cancelAllTransitions();    end    return menuGroup end 