-- Code created by Kwik - Copyright: kwiksher.com -- Version: 1.9.7a module(..., package.seeall)  function new() 
    local menuGroup = display.newGroup() 
    local disposeAudios     local disposeTweens     local vlns_audio = audio.loadSound(audioDir.."v22.mp3" )     local path = system.pathForFile( "SpoonAndTheMoonPart2.txt", system.DocumentsDirectory ) 
    local file = io.open( path, "w+" ) 
    file:write( _G.kwk_currentPage ) 
    io.close( file ) 

    local drawScreen = function()

		 navigation.DisplayDevelopmentVersion()
		menuGroup.navigator = navigation.InsertNavigation{}


local vlns         local CH12PG12  --(2) regular layer        CH12PG12 = display.newImageRect( imageDir.. "p186_ch12pg12.png", 768, 1024 );        CH12PG12.x = 384; CH12PG12.y = 512; CH12PG12.alpha = 1; CH12PG12.oldAlpha = 1        menuGroup:insert(CH12PG12)        menuGroup.CH12PG12 = CH12PG12        local onvlnsTouch = function(event)           if event.phase=="ended" then               local myChannel = 2              local isChannelPlaying = audio.isChannelPlaying(myChannel)              if isChannelPlaying then                 --nothing              else                 audio.play( vlns_audio, {channel=myChannel} )              end           end        end --(10) regular layer        vlns = ui.newButton{            defaultSrc=imageDir.."p186_vlns.png",            defaultX = 430,            defaultY = 28,            overSrc=imageDir.."p186_vlns.png",            overX = 430,            overY = 28,            onRelease=onvlnsTouch,            id="vlnsButton"        }        vlns.x = 348; vlns.y = 577; vlns.alpha = 1; vlns.oldAlpha = 1        menuGroup:insert(vlns)        menuGroup.vlns = vlns          local function flip (event)           local spacer = 180            if event.phase =="ended" then               if event.xStart < event.x and (event.x - event.xStart) >= spacer then                 if (_G.kwk_currentPage > 1) then                      disposeAudios()                     disposeTweens()                     director:changeScene( "page_".._G.kwk_currentPage-1, "moveFromLeft" )                 end              elseif event.xStart > event.x and (event.xStart-event.x) >= spacer then                  if (_G.kwk_currentPage < numPages) then                      disposeAudios()                     disposeTweens()                     director:changeScene("page_".._G.kwk_currentPage+1, "moveFromRight")                 end              end           end        end        CH12PG12:addEventListener("touch", flip)    end    drawScreen()    function disposeAudios(event)                    audio.stop(2); audio.dispose(vlns_audio); vlns_audio = nil                           audio.stop(3); audio.dispose(kwkBindex_audio); kwkBindex_audio = nil                        end    function disposeTweens(event)       cancelAllTweens();       cancelAllTimers();       cancelAllTransitions();    end    return menuGroup end 