-- Code created by Kwik - Copyright: kwiksher.com -- Version: 1.9.7a module(..., package.seeall)  function new() 
    local menuGroup = display.newGroup() 
    local disposeAudios     local disposeTweens     local bars_audio = audio.loadSound(audioDir.."click.mp3" )     local path = system.pathForFile( "SpoonAndTheMoonPart2.txt", system.DocumentsDirectory ) 
    local file = io.open( path, "w+" ) 
    file:write( _G.kwk_currentPage ) 
    io.close( file ) 

    local drawScreen = function()

		 navigation.DisplayDevelopmentVersion()
		menuGroup.navigator = navigation.InsertNavigation{}
        local showhide         local bars
local CH13PG1  --(2) regular layer        CH13PG1 = display.newImageRect( imageDir.. "p192_ch13pg1.png", 768, 1024 );        CH13PG1.x = 384; CH13PG1.y = 512; CH13PG1.alpha = 1; CH13PG1.oldAlpha = 1        menuGroup:insert(CH13PG1)        menuGroup.CH13PG1 = CH13PG1 


        local onbarsTouch = function(event)           if event.phase=="ended" then                  if showhide.alpha == 0 then                    transitionStash.newTransition_108 = transition.to( showhide, {alpha=showhide.oldAlpha, time=1000, delay=0})                 else                    transitionStash.newTransition_108 = transition.to( showhide, {alpha=0, time=1000, delay=0})                 end              local myChannel = 2              local isChannelPlaying = audio.isChannelPlaying(myChannel)              if isChannelPlaying then                 --nothing              else                 audio.play( bars_audio, {channel=myChannel} )              end           end        end --(10) regular layer        bars = ui.newButton{            defaultSrc=imageDir.."p192_bars.png",            defaultX = 133,            defaultY = 258,            overSrc=imageDir.."p192_bars.png",            overX = 133,            overY = 258,            onRelease=onbarsTouch,            id="barsButton"        }        bars.x = 77; bars.y = 760; bars.alpha = 1; bars.oldAlpha = 1        menuGroup:insert(bars)        menuGroup.bars = bars --(2) regular layer        showhide = display.newImageRect( imageDir.. "p192_showhide.png", 412, 138 );        showhide.x = 284; showhide.y = 677; showhide.alpha = 1; showhide.oldAlpha = 1        menuGroup:insert(showhide)        menuGroup.showhide = showhide        showhide.alpha = 0          local function flip (event)           local spacer = 180            if event.phase =="ended" then               if event.xStart < event.x and (event.x - event.xStart) >= spacer then                 if (_G.kwk_currentPage > 1) then                      disposeAudios()                     disposeTweens()                     director:changeScene( "page_".._G.kwk_currentPage-1, "moveFromLeft" )                 end              elseif event.xStart > event.x and (event.xStart-event.x) >= spacer then                  if (_G.kwk_currentPage < numPages) then                      disposeAudios()                     disposeTweens()                     director:changeScene("page_".._G.kwk_currentPage+1, "moveFromRight")                 end              end           end        end        CH13PG1:addEventListener("touch", flip)    end    drawScreen()    function disposeAudios(event)                    audio.stop(2); audio.dispose(bars_audio); bars_audio = nil                           audio.stop(3); audio.dispose(kwkBindex_audio); kwkBindex_audio = nil                        end    function disposeTweens(event)       cancelAllTweens();       cancelAllTimers();       cancelAllTransitions();    end    return menuGroup end 