-- Code created by Kwik - Copyright: kwiksher.com -- Version: 1.9.7a module(..., package.seeall)  function new() 
    local menuGroup = display.newGroup() 
    local disposeAudios     local disposeTweens     local spoony_audio = audio.loadSound(audioDir.."click.mp3" )     local path = system.pathForFile( "SpoonAndTheMoonPart2.txt", system.DocumentsDirectory ) 
    local file = io.open( path, "w+" ) 
    file:write( _G.kwk_currentPage ) 
    io.close( file ) 

    local drawScreen = function()

		 navigation.DisplayDevelopmentVersion()
		menuGroup.navigator = navigation.InsertNavigation{}


local showhide         local spoony         local BG  --(2) regular layer        BG = display.newImageRect( imageDir.. "p147_ch10pg3.png", 768, 1024 );        BG.x = 384; BG.y = 512; BG.alpha = 1; BG.oldAlpha = 1        menuGroup:insert(BG)        menuGroup.BG = BG        local onspoonyTouch = function(event)           if event.phase=="ended" then                  if showhide.alpha == 0 then                    transitionStash.newTransition_488 = transition.to( showhide, {alpha=showhide.oldAlpha, time=1000, delay=0})                 else                    transitionStash.newTransition_488 = transition.to( showhide, {alpha=0, time=1000, delay=0})                 end              local myChannel = 2              local isChannelPlaying = audio.isChannelPlaying(myChannel)              if isChannelPlaying then                 --nothing              else                 audio.play( spoony_audio, {channel=myChannel} )              end           end        end --(10) regular layer        spoony = ui.newButton{            defaultSrc=imageDir.."p147_spoony.png",            defaultX = 129,            defaultY = 497,            overSrc=imageDir.."p147_spoony.png",            overX = 129,            overY = 497,            onRelease=onspoonyTouch,            id="spoonyButton"        }        spoony.x = 116; spoony.y = 741; spoony.alpha = 1; spoony.oldAlpha = 1        menuGroup:insert(spoony)        menuGroup.spoony = spoony --(2) regular layer        showhide = display.newImageRect( imageDir.. "p147_showhide.png", 412, 246 );        showhide.x = 334; showhide.y = 554; showhide.alpha = 1; showhide.oldAlpha = 1        menuGroup:insert(showhide)        menuGroup.showhide = showhide        showhide.alpha = 0 --flip   end    drawScreen()    function disposeAudios(event)                    audio.stop(2); audio.dispose(spoony_audio); spoony_audio = nil                           audio.stop(3); audio.dispose(kwkBindex_audio); kwkBindex_audio = nil                        end    function disposeTweens(event)       cancelAllTweens();       cancelAllTimers();       cancelAllTransitions();    end    return menuGroup end 