-- Code created by Kwik - Copyright: kwiksher.com -- Version: 1.9.7a module(..., package.seeall)  function new() 
    local menuGroup = display.newGroup() 
    local disposeAudios     local disposeTweens     local wine_audio = audio.loadSound(audioDir.."glug.mp3" )     local path = system.pathForFile( "SpoonAndTheMoonPart2.txt", system.DocumentsDirectory ) 
    local file = io.open( path, "w+" ) 
    file:write( _G.kwk_currentPage ) 
    io.close( file ) 

    local drawScreen = function()

		 navigation.DisplayDevelopmentVersion()
		menuGroup.navigator = navigation.InsertNavigation{}


local wine         local CH9PG6  --(2) regular layer        CH9PG6 = display.newImageRect( imageDir.. "p133_ch9pg6.png", 768, 1024 );        CH9PG6.x = 384; CH9PG6.y = 512; CH9PG6.alpha = 1; CH9PG6.oldAlpha = 1        menuGroup:insert(CH9PG6)        menuGroup.CH9PG6 = CH9PG6        local onwineTouch = function(event)           if event.phase=="ended" then               local myChannel = 2              local isChannelPlaying = audio.isChannelPlaying(myChannel)              if isChannelPlaying then                 --nothing              else                 audio.play( wine_audio, {channel=myChannel} )              end           end        end --(10) regular layer        wine = ui.newButton{            defaultSrc=imageDir.."p133_wine.png",            defaultX = 169,            defaultY = 433,            overSrc=imageDir.."p133_wine.png",            overX = 169,            overY = 433,            onRelease=onwineTouch,            id="wineButton"        }        wine.x = 125; wine.y = 751; wine.alpha = 1; wine.oldAlpha = 1        menuGroup:insert(wine)        menuGroup.wine = wine          local function flip (event)           local spacer = 180            if event.phase =="ended" then               if event.xStart < event.x and (event.x - event.xStart) >= spacer then                 if (_G.kwk_currentPage > 1) then                      disposeAudios()                     disposeTweens()                     director:changeScene( "page_".._G.kwk_currentPage-1, "moveFromLeft" )                 end              elseif event.xStart > event.x and (event.xStart-event.x) >= spacer then                  if (_G.kwk_currentPage < numPages) then                      disposeAudios()                     disposeTweens()                     director:changeScene("page_".._G.kwk_currentPage+1, "moveFromRight")                 end              end           end        end        CH9PG6:addEventListener("touch", flip)    end    drawScreen()    function disposeAudios(event)                    audio.stop(2); audio.dispose(wine_audio); wine_audio = nil                           audio.stop(3); audio.dispose(kwkBindex_audio); kwkBindex_audio = nil                        end    function disposeTweens(event)       cancelAllTweens();       cancelAllTimers();       cancelAllTransitions();    end    return menuGroup end 