-- Code created by Kwik - Copyright: kwiksher.com 
-- Version: 2.4.6 

module(..., package.seeall) 
 function new()     local menuGroup = display.newGroup()     local disposeAudios     local disposeTweens     local ants_audio = audio.loadSound(audioDir .. "click.mp3", system.ResourceDirectory)      -- local kwkBindex_audio = audio.loadSound(audioDir .. "indexflip.mp3", system.ResourceDirectory)      statusreport.debugPrint("----------------"); statusreport.debugPrint(""); statusreport.debugPrint("New Page")     statusreport.debugPrint("The current page is: " .. _G.kwk_currentPage)     local path = system.pathForFile( "SpoonAndTheMoonPart1.txt", system.DocumentsDirectory )     local file = io.open( path, "w+" )     file:write( _G.kwk_currentPage )     io.close( file )   local drawScreen = function()

  navigation.DisplayDevelopmentVersion()
		menuGroup.navigator = navigation.InsertNavigation{}
       local chpt1pv         local chpt1pvover         local howhide         local ants         --local PageXCorner         local BG         BG = display.newImageRect(imageDir .. "p63_ch04pg4.png", 768, 1024 );        BG.x = 384; BG.y = 512; BG.alpha = 1; BG.oldAlpha = 1        menuGroup:insert(BG)        menuGroup.BG = BG --XPageXCornerX--XpaperXcornerX       local onantsTouch = function(event)           if event.phase=="ended" then                  if howhide.alpha == 0 then                    transitionStash.newTransition_262 = transition.to( howhide, {alpha=howhide.oldAlpha, time=1000, delay=0})                 else                    transitionStash.newTransition_262 = transition.to( howhide, {alpha=0, time=1000, delay=0})                 end              local myChannel = 2              local isChannelPlaying = audio.isChannelPlaying(myChannel)              if isChannelPlaying then                 --nothing              else                 audio.play( ants_audio, {channel=myChannel} )              end           end        end        ants = ui.newButton{            defaultSrc= imageDir .."p63_ants.png",            defaultX = 77,            defaultY = 695,            overSrc= imageDir .."p63_ants.png",            overX = 77,            overY = 695,            onRelease=onantsTouch,            id="antsButton"        }        ants.x = 38; ants.y = 471; ants.alpha = 1; ants.oldAlpha = 1        menuGroup:insert(ants)        menuGroup.ants = ants        howhide = display.newImageRect(imageDir .. "p63_howhide.png", 349, 286 );        howhide.x = 184; howhide.y = 495; howhide.alpha = 1; howhide.oldAlpha = 1        menuGroup:insert(howhide)        menuGroup.howhide = howhide        local onchpt1pvTouch = function(event)           if event.phase=="ended" then           media.playVideo( "movie_part1_ants.mp4", system.ResourceDirectory, false )           end        end        chpt1pv = ui.newButton{            defaultSrc= imageDir .."p63_chpt1pv.png",            defaultX = 102,            defaultY = 102,            overSrc= imageDir .."p63_chpt1pvover.png",            overX = 102,            overY = 102,            onRelease=onchpt1pvTouch,            id="chpt1pvButton"        }        chpt1pv.x = 385; chpt1pv.y = 863; chpt1pv.alpha = 1; chpt1pv.oldAlpha = 1        menuGroup:insert(chpt1pv)        menuGroup.chpt1pv = chpt1pv              howhide.alpha = 0 
	end
   drawScreen()    function disposeAudios(event)                    audio.stop(2); audio.dispose(ants_audio); ants_audio = nil                            -- audio.stop(13); audio.dispose(kwkBindex_audio); kwkBindex_audio = nil                        end    function disposeTweens(event)       cancelAllTweens();       cancelAllTimers();       cancelAllTransitions();    end    return menuGroup end 