-- Code created by Kwik - Copyright: kwiksher.com 
-- Version: 2.4.6 

module(..., package.seeall) 
 function new()     local menuGroup = display.newGroup()     local disposeAudios     local disposeTweens      -- local kwkBindex_audio = audio.loadSound(audioDir .. "indexflip.mp3", system.ResourceDirectory)      statusreport.debugPrint("----------------"); statusreport.debugPrint(""); statusreport.debugPrint("New Page")     statusreport.debugPrint("The current page is: " .. _G.kwk_currentPage)     local path = system.pathForFile( "SpoonAndTheMoonPart1.txt", system.DocumentsDirectory )     local file = io.open( path, "w+" )     file:write( _G.kwk_currentPage )     io.close( file )   local drawScreen = function()

  navigation.DisplayDevelopmentVersion()
		menuGroup.navigator = navigation.InsertNavigation{}


       local bubble4         local bubble3         local bubble2         local bubble1         --local PageXCorner         local BG         BG = display.newImageRect(imageDir .. "p3_bg.png", 768, 1024 );        BG.x = 384; BG.y = 512; BG.alpha = 1; BG.oldAlpha = 1        menuGroup:insert(BG)        menuGroup.BG = BG --XPageXCornerX       --XPageXCornerX              bubble1 = display.newImageRect(imageDir .. "p3_bubble1.png", 164, 171 );        bubble1.x = 238; bubble1.y = 1297; bubble1.alpha = 1; bubble1.oldAlpha = 1        menuGroup:insert(bubble1)        menuGroup.bubble1 = bubble1        bubble2 = display.newImageRect(imageDir .. "p3_bubble2.png", 78, 81 );        bubble2.x = 531; bubble2.y = 1234; bubble2.alpha = 1; bubble2.oldAlpha = 1        menuGroup:insert(bubble2)        menuGroup.bubble2 = bubble2        bubble3 = display.newImageRect(imageDir .. "p3_bubble3.png", 32, 33 );        bubble3.x = 461; bubble3.y = 1224; bubble3.alpha = 1; bubble3.oldAlpha = 1        menuGroup:insert(bubble3)        menuGroup.bubble3 = bubble3        bubble4 = display.newImageRect(imageDir .. "p3_bubble4.png", 32, 33 );        bubble4.x = 191; bubble4.y = 1224; bubble4.alpha = 1; bubble4.oldAlpha = 1        menuGroup:insert(bubble4)        menuGroup.bubble4 = bubble4        --2        gtStash.gt_bubble4_359= gtween.new( bubble4, 13, { x = 191, y = -284, rotation = 0, xScale = 1, yScale = 1, alpha=1}, {ease = gtween.easing.linear, repeatCount = math.huge, reflect = false,  delay=5})        --2        gtStash.gt_bubble3_370= gtween.new( bubble3, 13, { x = 461, y = -284, rotation = 0, xScale = 1, yScale = 1, alpha=1}, {ease = gtween.easing.linear, repeatCount = math.huge, reflect = false,  delay=3})        --2        gtStash.gt_bubble2_380= gtween.new( bubble2, 12, { x = 531, y = -260, rotation = 0, xScale = 1, yScale = 1, alpha=1}, {ease = gtween.easing.linear, repeatCount = math.huge, reflect = false,  delay=5})        local onEndbubble1_391 = function()            bubble1.isVisible = false;            bubble1.x = 238; bubble1.y = 1297;            bubble1.xScale = 1;bubble1.yScale = 1;            bubble1.alpha = 1; bubble1.rotation = 0            bubble1.isVisible = true;         end        --1 --1        gtStash.gt_bubble1_391= gtween.new( bubble1, 12, { x = 259, y = -215, rotation = 0, xScale = 1, yScale = 1, alpha=1}, {ease = gtween.easing.linear, repeatCount = math.huge, reflect = false,  delay=7, onComplete = onEndbubble1_391 }) 
	end
   drawScreen()    function disposeAudios(event)                     -- audio.stop(13); audio.dispose(kwkBindex_audio); kwkBindex_audio = nil                        end    function disposeTweens(event)       cancelAllTweens();       cancelAllTimers();       cancelAllTransitions();    end    return menuGroup end 