-- Code created by Kwik - Copyright: kwiksher.com 
-- Version: 2.4.6 

module(..., package.seeall) 
 function new()     local menuGroup = display.newGroup()     local fish_audio = audio.loadSound(audioDir .. "click.mp3", system.ResourceDirectory)     statusreport.debugPrint("----------------"); statusreport.debugPrint(""); statusreport.debugPrint("New Page")     statusreport.debugPrint("The current page is: " .. _G.kwk_currentPage)     local path = system.pathForFile( "SpoonAndTheMoonPart1.txt", system.CachesDirectory )     local file = io.open( path, "w+" )     file:write( _G.kwk_currentPage )     io.close( file )   local drawScreen = function()

		navigation.DisplayDevelopmentVersion()
		menuGroup.navigator = navigation.InsertNavigation{}
       local showhide         local fish         local BG         BG = display.newImageRect(imageDir .. "p50_ch03pg4.png", 768, 1024 );        BG.x = 384; BG.y = 512; BG.alpha = 1; BG.oldAlpha = 1        menuGroup:insert(BG)        menuGroup.BG = BG        local onfishTouch = function(event)           if event.phase=="ended" then                  if showhide.alpha == 0 then                    transitionStash.newTransition_406 = transition.to( showhide, {alpha=showhide.oldAlpha, time=1000, delay=0})                 else                    transitionStash.newTransition_406 = transition.to( showhide, {alpha=0, time=1000, delay=0})                 end              local myChannel = 2              local isChannelPlaying = audio.isChannelPlaying(myChannel)              if isChannelPlaying then                 --nothing              else                 audio.play( fish_audio, {channel=myChannel} )              end           end        end        fish = ui.newButton{            defaultSrc= imageDir .."p50_fish.png",            defaultX = 530,            defaultY = 178,            overSrc= imageDir .."p50_fish.png",            overX = 530,            overY = 178,            onRelease=onfishTouch,            id="fishButton"        }        fish.x = 383; fish.y = 767; fish.alpha = 1; fish.oldAlpha = 1        menuGroup:insert(fish)        menuGroup.fish = fish        showhide = display.newImageRect(imageDir .. "p50_showhide.png", 549, 267 );        showhide.x = 384; showhide.y = 566; showhide.alpha = 1; showhide.oldAlpha = 1        menuGroup:insert(showhide)        menuGroup.showhide = showhide              showhide.alpha = 0 
	end
   drawScreen()    return menuGroup end 