-- Code created by Kwik - Copyright: kwiksher.com 
-- Version: 2.4.6 

module(..., package.seeall) 
 function new()     local menuGroup = display.newGroup()     local disposeAudios     local disposeTweens     local crow_flying_aud171 = audio.loadSound(audioDir .. "crow_flying.mp3", system.ResourceDirectory)     local bitty_audio = audio.loadSound(audioDir .. "click.mp3", system.ResourceDirectory)      -- local kwkBindex_audio = audio.loadSound(audioDir .. "indexflip.mp3", system.ResourceDirectory)      statusreport.debugPrint("----------------"); statusreport.debugPrint(""); statusreport.debugPrint("New Page")     statusreport.debugPrint("The current page is: " .. _G.kwk_currentPage)     local path = system.pathForFile( "SpoonAndTheMoonPart1.txt", system.DocumentsDirectory )     local file = io.open( path, "w+" )     file:write( _G.kwk_currentPage )     io.close( file )   local drawScreen = function()

  navigation.DisplayDevelopmentVersion()
		menuGroup.navigator = navigation.InsertNavigation{}
       local showhide         local bitty         local conrer         local BG         BG = display.newImageRect(imageDir .. "p47_ch03pg1.png", 768, 1024 );        BG.x = 384; BG.y = 512; BG.alpha = 1; BG.oldAlpha = 1        menuGroup:insert(BG)        menuGroup.BG = BG        local onbittyTouch = function(event)           if event.phase=="ended" then                  if showhide.alpha == 0 then                    transitionStash.newTransition_934 = transition.to( showhide, {alpha=showhide.oldAlpha, time=1000, delay=0})                 else                    transitionStash.newTransition_934 = transition.to( showhide, {alpha=0, time=1000, delay=0})                 end              local myChannel = 3              local isChannelPlaying = audio.isChannelPlaying(myChannel)              if isChannelPlaying then                 --nothing              else                 audio.play( bitty_audio, {channel=myChannel} )              end           end        end        bitty = ui.newButton{            defaultSrc= imageDir .."p47_bitty.png",            defaultX = 236,            defaultY = 471,            overSrc= imageDir .."p47_bitty.png",            overX = 236,            overY = 471,            onRelease=onbittyTouch,            id="bittyButton"        }        bitty.x = 159; bitty.y = 435; bitty.alpha = 1; bitty.oldAlpha = 1        menuGroup:insert(bitty)        menuGroup.bitty = bitty        showhide = display.newImageRect(imageDir .. "p47_showhide.png", 412, 297 );        showhide.x = 424; showhide.y = 393; showhide.alpha = 1; showhide.oldAlpha = 1        menuGroup:insert(showhide)        menuGroup.showhide = showhide              showhide.alpha = 0 
	end
   drawScreen()    function disposeAudios(event)                    audio.stop(2); audio.dispose(crow_flying_aud171); crow_flying_aud171 =nil       audio.stop(3); audio.dispose(bitty_audio); bitty_audio = nil                            -- audio.stop(13); audio.dispose(kwkBindex_audio); kwkBindex_audio = nil                        end    function disposeTweens(event)       cancelAllTweens();       cancelAllTimers();       cancelAllTransitions();    end    local myClosure_crow_flying_aud171 = function()       audio.play(crow_flying_aud171, {  channel=2, loops=0, fadein=500 } )    end    timerStash.newTimer_171 = timer.performWithDelay(0, myClosure_crow_flying_aud171, 1)    return menuGroup end 