-- Code created by Kwik - Copyright: kwiksher.com 
-- Version: 2.4.6 

module(..., package.seeall) 
 function new()     local menuGroup = display.newGroup()     local saw_audio = audio.loadSound(audioDir .. "saw2.mp3", system.ResourceDirectory)     local saw2_audio = audio.loadSound(audioDir .. "drill.mp3", system.ResourceDirectory)     local saw3_audio = audio.loadSound(audioDir .. "saw.mp3", system.ResourceDirectory) 
    statusreport.debugPrint("----------------"); statusreport.debugPrint(""); statusreport.debugPrint("New Page") 
    statusreport.debugPrint("The current page is: " .. _G.kwk_currentPage) 

    local path = system.pathForFile( "SpoonAndTheMoonPart1.txt", system.CachesDirectory )     local file = io.open( path, "w+" )     file:write( _G.kwk_currentPage )     io.close( file )   local drawScreen = function()

		navigation.DisplayDevelopmentVersion()
		menuGroup.navigator = navigation.InsertNavigation{}
       local saw3         local saw2         local saw         local BG         BG = display.newImageRect(imageDir .. "p44_ch02pg20.png", 768, 1024 );        BG.x = 384; BG.y = 512; BG.alpha = 1; BG.oldAlpha = 1        menuGroup:insert(BG)        menuGroup.BG = BG        local onsawTouch = function(event)           if event.phase=="ended" then               local myChannel = 2              local isChannelPlaying = audio.isChannelPlaying(myChannel)              if isChannelPlaying then                 --nothing              else                 audio.play( saw_audio, {channel=myChannel} )              end           end        end        saw = ui.newButton{            defaultSrc= imageDir .."p44_saw.png",            defaultX = 148,            defaultY = 120,            overSrc= imageDir .."p44_saw.png",            overX = 148,            overY = 120,            onRelease=onsawTouch,            id="sawButton"        }        saw.x = 675; saw.y = 793; saw.alpha = 1; saw.oldAlpha = 1        menuGroup:insert(saw)        menuGroup.saw = saw        local onsaw2Touch = function(event)           if event.phase=="ended" then               local myChannel = 3              local isChannelPlaying = audio.isChannelPlaying(myChannel)              if isChannelPlaying then                 --nothing              else                 audio.play( saw2_audio, {channel=myChannel} )              end           end        end        saw2 = ui.newButton{            defaultSrc= imageDir .."p44_saw2.png",            defaultX = 170,            defaultY = 131,            overSrc= imageDir .."p44_saw2.png",            overX = 170,            overY = 131,            onRelease=onsaw2Touch,            id="saw2Button"        }        saw2.x = 145; saw2.y = 140; saw2.alpha = 1; saw2.oldAlpha = 1        menuGroup:insert(saw2)        menuGroup.saw2 = saw2        local onsaw3Touch = function(event)           if event.phase=="ended" then               local myChannel = 4              local isChannelPlaying = audio.isChannelPlaying(myChannel)              if isChannelPlaying then                 --nothing              else                 audio.play( saw3_audio, {channel=myChannel} )              end           end        end        saw3 = ui.newButton{            defaultSrc= imageDir .."p44_saw3.png",            defaultX = 164,            defaultY = 127,            overSrc= imageDir .."p44_saw3.png",            overX = 164,            overY = 127,            onRelease=onsaw3Touch,            id="saw3Button"        }        saw3.x = 647; saw3.y = 182; saw3.alpha = 1; saw3.oldAlpha = 1        menuGroup:insert(saw3)        menuGroup.saw3 = saw3 --local PageZZCorner
	end
   drawScreen()    return menuGroup end 